// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Drill struct {
	DrillID    uuid.UUID   `json:"drillId"`
	DrillName  string      `json:"drillName"`
	Category   pgtype.Text `json:"category"`
	Difficulty pgtype.Text `json:"difficulty"`
}

type PlayerPerformance struct {
	PlayerPerformanceID uuid.UUID   `json:"playerPerformanceId"`
	PlayerID            uuid.UUID   `json:"playerId"`
	DrillID             uuid.UUID   `json:"drillId"`
	Date                pgtype.Date `json:"date"`
	Attempts            pgtype.Int4 `json:"attempts"`
	Successful          pgtype.Int4 `json:"successful"`
}

type User struct {
	UserID    uuid.UUID   `json:"userId"`
	Username  string      `json:"username"`
	Passhash  string      `json:"passhash"`
	Email     string      `json:"email"`
	Firstname pgtype.Text `json:"firstname"`
	Lastname  pgtype.Text `json:"lastname"`
}
