// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Drill struct {
	DrillID    uuid.UUID   `json:"drillId"`
	DrillName  string      `json:"drillName"`
	Category   pgtype.Text `json:"category"`
	Difficulty pgtype.Text `json:"difficulty"`
}

type Goal struct {
	GoalID   uuid.UUID `json:"goalId"`
	GoalType string    `json:"goalType"`
	GoalName string    `json:"goalName"`
}

type PlayerGoal struct {
	PlayerGoalID uuid.UUID   `json:"playerGoalId"`
	PlayerID     uuid.UUID   `json:"playerId"`
	GoalID       uuid.UUID   `json:"goalId"`
	CurrentValue pgtype.Int4 `json:"currentValue"`
	GoalValue    int32       `json:"goalValue"`
}

type PlayerPerformance struct {
	PlayerPerformanceID uuid.UUID   `json:"playerPerformanceId"`
	PlayerID            uuid.UUID   `json:"playerId"`
	DrillID             uuid.UUID   `json:"drillId"`
	Date                pgtype.Date `json:"date"`
	Attempts            pgtype.Int4 `json:"attempts"`
	Successful          pgtype.Int4 `json:"successful"`
}

type Session struct {
	SessionID   uuid.UUID   `json:"sessionId"`
	SessionType string      `json:"sessionType"`
	Date        pgtype.Date `json:"date"`
	Location    pgtype.Text `json:"location"`
	UserID      uuid.UUID   `json:"userId"`
	SessionName string      `json:"sessionName"`
}

type SessionPerformance struct {
	SessionPerformanceID uuid.UUID `json:"sessionPerformanceId"`
	SessionID            uuid.UUID `json:"sessionId"`
	PlayerPerformanceID  uuid.UUID `json:"playerPerformanceId"`
}

type User struct {
	UserID    uuid.UUID   `json:"userId"`
	Username  string      `json:"username"`
	Passhash  string      `json:"passhash"`
	Email     string      `json:"email"`
	Firstname pgtype.Text `json:"firstname"`
	Lastname  pgtype.Text `json:"lastname"`
}
